config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'homepage/index'

  resources :sessions, only: %i[ destroy new create ]

  resources :users, only: %i[new create show]

  get 'sign_up', to: 'users#new', as: 'sign_up'

  get 'sign_in', to: 'sessions#new', as: 'sign_in'

  get 'sign_out', to: 'sessions#destroy', as: 'sign_out'

  resources :categories, except: %i[ index edit]

  resources :articles, except: %i[ index ] do

    resources :votes, only: %i[create destroy]

  end

  root 'homepage#index'
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { maximum: 40 }
  validates :text, presence: true
  validates :image, presence: true

  mount_uploader :image, ImageUploader
  belongs_to :author, class_name: 'User'

  has_many :categories_articles
  has_many :categories, through: :categories_articles, dependent: :destroy
  has_many :votes, class_name: 'Vote', foreign_key: 'article_id', dependent: :destroy

  def self.default_image
    'https://res.cloudinary.com/lifestyle-articles/image/upload/v1604647869/sample.jpg'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all
  end

  def show; end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        CategoriesArticle.create(category_id: @category, article_id: @article.id)
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        category = CategoriesArticle.where(article_id: @article.id)
        category[0].category_id = article_params[:category_id]
        category[0].save
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :image, category_ids: [])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_author_name(article)
    article.author.name
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</p>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_area :text, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label 'Category'%><br />
    <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control-file w-100 vh-60' %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Article', class: 'btn-block'%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="article-form-center mt-4">
  <h1>Editing Article</h1>

  <%= render 'form', article: @article %>
 
  <div class="px-2">
    <%= link_to 'Show', @article %> |
    <%= link_to 'Back', articles_path %>
  </div>
</div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= article.image %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<%= provide(:title, 'Article') %>

<div class="article-form-center">
  <h1>New Article</h1>

  <%= render 'form', article: @article %>

  <p class="mt-3">
    <%= link_to 'Back', articles_path %>
  </p>
</div>

app/views/articles/show.html.erb
<%= provide(:title, 'View Article') %>

<div class="container mt-2">
  <div class="card single-article">
    <div class="card-body row">
      <div class="col-6">
        <h5 class="card-title"><%= @article.title %></h5>
        <p class="underline"></p>
        <div class="card-text">
          <p class="text"><%= @article.text %></p>
          <p class="votes-count">Votes: <i><%= count_votes_for_article(@article) %></i></p>
          <p class="author">Authored by: <strong><%= article_author_name(@article)%></strong> </p>
        </div>
      </div>

      <div class="col-6 article-image" style="background-image: url(<%= @article.image %>)"></div>
    </div>

    <div class="card-footer">
      <button class='vote btn btn-sm btn-warning'>
        <%= up_or_downvote(@article)  %>
      </button>

      <% if @article.author.id == current_user.id %>
        <button class="btn btn-sm bg-global">
          <%= link_to 'Edit', edit_article_path(@article) %>
        </button>
        <button class="btn btn-sm bg-global">
          <%= link_to 'Back', category_path(@article) %>
        </button>
      <% end %>
    </div>
  </div>
</div>