config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'homepage/index'

  resources :sessions, only: %i[ destroy new create ]

  resources :users, only: %i[new create show]

  get 'sign_up', to: 'users#new', as: 'sign_up'

  get 'sign_in', to: 'sessions#new', as: 'sign_in'

  get 'sign_out', to: 'sessions#destroy', as: 'sign_out'

  resources :categories, except: %i[ index edit]

  resources :articles, except: %i[ index ] do

    resources :votes, only: %i[create destroy]

  end

  root 'homepage#index'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :articles, class_name: 'Article', foreign_key: :author_id, dependent: :destroy
  has_many :votes, class_name: 'Vote', foreign_key: 'user_id', dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_path, notice: 'You have signed up successfully' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to homepage_index_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to homepage_index_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Sign Up', class: 'btn-block'%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign Up') %>

<div class="container mt-5 pt-2">
  <div class="form-center">
    <div class="my-auto h-100">
    <h1>Sign Up</h1>

    <%= render 'form', user: @user %>

    <p class="mt-3">
      <%= link_to 'Sign In', new_session_path %>
    </p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, 'Profile') %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Back', root_path %>