config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'homepage/index'

  resources :sessions, only: %i[ destroy new create ]

  resources :users, only: %i[new create show]

  get 'sign_up', to: 'users#new', as: 'sign_up'

  get 'sign_in', to: 'sessions#new', as: 'sign_in'

  get 'sign_out', to: 'sessions#destroy', as: 'sign_out'

  resources :categories, except: %i[ index edit]

  resources :articles, except: %i[ index ] do

    resources :votes, only: %i[create destroy]

  end

  root 'homepage#index'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light border-bottom">
  <!-- Brand -->
  <a href="<%= root_path %>" class="navbar-brand">
    <span class="primary"> SIB</span>LI<span class="primary">FE</span>
  </a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsenav">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse justify-content-end" id="collapsenav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <% Category.all.each do |category| %>
          <li class="nav-item">
            <%= link_to category.name, category, class: 'nav-link'%>
          </li>
        <% end %>
        <li class="nav-item bg-global">
            <%= link_to 'Post An Article', new_article_path, class: "nav-link text-light" %>
        </li>
        <li class="nav-item ml-5">
          <%= link_to current_user.name, '#', class: 'nav-link username' %>
        </li>
        <li class="nav-item">
            <%= link_to 'Sign Out', sign_out_path, class: "nav-link" %>
        </li>
      <% else %>
        <% Category.all.each do |category| %>
          <li class="nav-item">
            <%= link_to category.name, category, class: 'nav-link'%>
          </li>
        <% end %>
        <li class="nav-item">
            <%= link_to 'Sign In', new_session_path, class: "nav-link signin-btn text-info" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Sign Up', sign_up_path, class: "nav-link signup-btn text-info" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | SIBLIFE </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicons/favicon.ico' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/e2597287a1.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <%= render 'layouts/nav' %>
    </header>

    <div class="notifications">
      <% if notice.present? %>
        <div class="notice">
          <p class="text-center text-success"><%= notice %></p>
        </div>
      <% elsif alert.present? %>
        <div class="alert">
          <p class="text-center text-danger"><%= alert %></p>
        </div>
      <% end %>
    </div>

    <main class="container-fluid">
      <div><%= yield %></div>
    </main>

    <footer class="footer p-0 m-0 container-fluid">
      <div class="row align-items-center m-0">
        <div class="col-sm mt-3">
          <p class="main-logo">
            <span class="primary"> SIB</span>LI<span class="primary">FE</span>
          </p>
        </div>

        <div class="col-sm mt-3">
          <p>
            <small class="policy">Privacy Policy <span class="text-light">|</span> Terms & Conditions</small>
            <small> &copy; 2020 Siblife. All rights reserved.</small>
          </p>
        </div>

        <div class="col-sm social-links mt-3">
          <p class="text-center">
            Contact Us: &nbsp;
            <span class="social-icon">
              <a href="https://www.twitter/ClaytonSiby" target="_blank" class="icon">
                <i class="fab fa-twitter"></i>
              </a>           
            </span>

            <span class="social-icon">
              <a href="https://www.facebook.com/clayton.siby.589/" target="_blank" class="icon">
                <i class="fab fa-facebook-f"></i>
              </a>           
            </span>

            <span class="social-icon">
              <a href="https://www.instagram/ClaytonSiby" target="_blank" class="icon">
                <i class="fab fa-instagram"></i>
              </a>           
            </span>
          </p>
        </div>
      </div>
    </footer>
  </body>
</html>